// Word bank for a beginner. tier 1 = short, very common words; tier 2 = 4-5 letters; tier 3 = longer.
// pic: an emoji (pixelized at runtime), "c:#hex" = paint blob of that colour, "n:3" = three dots.
(function () {
  const W = [
    // tier 1 ─ three-letter words
    ['cat', 'חתול', '🐱', 1, 'animal'], ['dog', 'כלב', '🐶', 1, 'animal'], ['fox', 'שועל', '🦊', 1, 'animal'],
    ['pig', 'חזיר', '🐷', 1, 'animal'], ['cow', 'פרה', '🐮', 1, 'animal'], ['bee', 'דבורה', '🐝', 1, 'animal'],
    ['owl', 'ינשוף', '🦉', 1, 'animal'], ['bat', 'עטלף', '🦇', 1, 'animal'], ['hen', 'תרנגולת', '🐔', 1, 'animal'],
    ['ant', 'נמלה', '🐜', 1, 'animal'],
    ['sun', 'שמש', '☀️', 1, 'thing'], ['hat', 'כובע', '🎩', 1, 'thing'], ['bed', 'מיטה', '🛏️', 1, 'thing'],
    ['cup', 'ספל', '☕', 1, 'thing'], ['box', 'קופסה', '📦', 1, 'thing'], ['key', 'מפתח', '🔑', 1, 'thing'],
    ['bag', 'תיק', '👜', 1, 'thing'], ['car', 'מכונית', '🚗', 1, 'thing'], ['bus', 'אוטובוס', '🚌', 1, 'thing'],
    ['pen', 'עט', '🖊️', 1, 'thing'], ['egg', 'ביצה', '🥚', 1, 'food'], ['gem', 'יהלום', '💎', 1, 'thing'],
    ['eye', 'עין', '👁️', 1, 'body'], ['ear', 'אוזן', '👂', 1, 'body'], ['arm', 'זרוע', '💪', 1, 'body'],
    ['red', 'אדום', 'c:#e0383a', 1, 'color'], ['one', 'אחת', 'n:1', 1, 'number'], ['two', 'שתיים', 'n:2', 1, 'number'],
    ['six', 'שש', 'n:6', 1, 'number'], ['ten', 'עשר', 'n:10', 1, 'number'], ['big', 'גדול', '🐘', 1, 'describe'],
    ['hot', 'חם', '🌶️', 1, 'describe'], ['run', 'לרוץ', '🏃', 1, 'action'], ['sad', 'עצוב', '😢', 1, 'describe'],
    // tier 2 ─ four / five letters
    ['fish', 'דג', '🐟', 2, 'animal'], ['bird', 'ציפור', '🐦', 2, 'animal'], ['frog', 'צפרדע', '🐸', 2, 'animal'],
    ['duck', 'ברווז', '🦆', 2, 'animal'], ['lion', 'אריה', '🦁', 2, 'animal'], ['bear', 'דוב', '🐻', 2, 'animal'],
    ['moon', 'ירח', '🌙', 2, 'thing'], ['star', 'כוכב', '⭐', 2, 'thing'], ['ball', 'כדור', '⚽', 2, 'thing'],
    ['book', 'ספר', '📖', 2, 'thing'], ['tree', 'עץ', '🌳', 2, 'thing'], ['fire', 'אש', '🔥', 2, 'thing'],
    ['door', 'דלת', '🚪', 2, 'thing'], ['ring', 'טבעת', '💍', 2, 'thing'], ['drum', 'תוף', '🥁', 2, 'thing'],
    ['boat', 'סירה', '⛵', 2, 'thing'], ['leaf', 'עלה', '🍃', 2, 'thing'], ['rock', 'אבן', '🪨', 2, 'thing'],
    ['sock', 'גרב', '🧦', 2, 'thing'], ['hand', 'יד', '✋', 2, 'body'],
    ['tooth', 'שן', '🦷', 3, 'body'], ['foot', 'כף רגל', '🦶', 2, 'body'], ['milk', 'חלב', '🥛', 2, 'food'],
    ['cake', 'עוגה', '🍰', 2, 'food'], ['corn', 'תירס', '🌽', 2, 'food'],
    ['blue', 'כחול', 'c:#3a6fe0', 2, 'color'], ['pink', 'ורוד', 'c:#ff8ccf', 2, 'color'],
    ['green', 'ירוק', 'c:#3fb54a', 2, 'color'], ['black', 'שחור', 'c:#26222c', 2, 'color'],
    ['white', 'לבן', 'c:#f4f1ea', 2, 'color'], ['brown', 'חום', 'c:#8a5a34', 2, 'color'],
    ['three', 'שלוש', 'n:3', 2, 'number'], ['four', 'ארבע', 'n:4', 2, 'number'], ['five', 'חמש', 'n:5', 2, 'number'],
    ['nine', 'תשע', 'n:9', 2, 'number'], ['cold', 'קר', '🥶', 2, 'describe'], ['happy', 'שמח', '😊', 2, 'describe'],
    ['small', 'קטן', '🐭', 2, 'describe'], ['swim', 'לשחות', '🏊', 2, 'action'], ['jump', 'לקפוץ', '🦘', 2, 'action'],
    ['sleep', 'לישון', '😴', 2, 'action'], ['eat', 'לאכול', '🍽️', 2, 'action'], ['house', 'בית', '🏠', 2, 'thing'],
    ['crown', 'כתר', '👑', 2, 'thing'],
    // tier 3 ─ longer words
    ['apple', 'תפוח', '🍎', 3, 'food'], ['bread', 'לחם', '🍞', 3, 'food'], ['pizza', 'פיצה', '🍕', 3, 'food'],
    ['banana', 'בננה', '🍌', 3, 'food'], ['dragon', 'דרקון', '🐉', 3, 'animal'], ['rabbit', 'ארנב', '🐰', 3, 'animal'],
    ['flower', 'פרח', '🌸', 3, 'thing'], ['castle', 'טירה', '🏰', 3, 'thing'], ['yellow', 'צהוב', 'c:#ffd23a', 3, 'color'],
    ['orange', 'כתום', 'c:#ff8a1c', 3, 'color'], ['purple', 'סגול', 'c:#9a4fd8', 3, 'color'],
    ['seven', 'שבע', 'n:7', 3, 'number'], ['eight', 'שמונה', 'n:8', 3, 'number'], ['water', 'מים', '💧', 3, 'thing'],
    ['bridge', 'גשר', '🌉', 3, 'thing'], ['potion', 'שיקוי', '🧪', 3, 'thing'], ['window', 'חלון', '🪟', 3, 'thing'],
    // more tier 2
    ['kite', 'עפיפון', '🪁', 2, 'thing'], ['ship', 'ספינה', '🚢', 2, 'thing'], ['shoe', 'נעל', '👟', 2, 'thing'],
    ['nose', 'אף', '👃', 2, 'body'], ['rain', 'גשם', '🌧️', 2, 'thing'], ['snow', 'שלג', '☃️', 2, 'thing'],
    ['horse', 'סוס', '🐴', 2, 'animal'], ['sheep', 'כבשה', '🐑', 2, 'animal'], ['mouse', 'עכבר', '🐁', 2, 'animal'],
    ['snake', 'נחש', '🐍', 2, 'animal'], ['tiger', 'נמר', '🐯', 2, 'animal'], ['zebra', 'זברה', '🦓', 2, 'animal'],
    ['robot', 'רובוט', '🤖', 2, 'thing'], ['clock', 'שעון', '⏰', 2, 'thing'], ['chair', 'כיסא', '🪑', 2, 'thing'],
    ['shirt', 'חולצה', '👕', 2, 'thing'], ['plane', 'מטוס', '✈️', 2, 'thing'], ['truck', 'משאית', '🚚', 2, 'thing'],
    ['train', 'רכבת', '🚂', 2, 'thing'], ['cloud', 'ענן', '☁️', 2, 'thing'], ['lemon', 'לימון', '🍋', 2, 'food'],
    ['mouth', 'פה', '👄', 2, 'body'], ['shell', 'צדף', '🐚', 2, 'thing'], ['angry', 'כועס', '😠', 2, 'describe'],
    ['sing', 'לשיר', '🎤', 2, 'action'], ['cook', 'לבשל', '🍳', 2, 'action'], ['ride', 'לרכוב', '🚴', 2, 'action'],
    // more tier 3
    ['turtle', 'צב', '🐢', 3, 'animal'], ['monkey', 'קוף', '🐒', 3, 'animal'], ['spider', 'עכביש', '🕷️', 3, 'animal'],
    ['rocket', 'טיל', '🚀', 3, 'thing'], ['pencil', 'עיפרון', '✏️', 3, 'thing'], ['guitar', 'גיטרה', '🎸', 3, 'thing'],
    ['cookie', 'עוגייה', '🍪', 3, 'food'], ['cheese', 'גבינה', '🧀', 3, 'food'], ['carrot', 'גזר', '🥕', 3, 'food'],
    ['grapes', 'ענבים', '🍇', 3, 'food'], ['cherry', 'דובדבן', '🍒', 3, 'food'], ['honey', 'דבש', '🍯', 3, 'food'],
    ['candle', 'נר', '🕯️', 3, 'thing'], ['island', 'אי', '🏝️', 3, 'thing'], ['dance', 'לרקוד', '💃', 3, 'action'],
    ['climb', 'לטפס', '🧗', 3, 'action'], ['paint', 'לצבוע', '🎨', 3, 'action'], ['laugh', 'לצחוק', '😂', 3, 'action'],
    // tier 4 ─ long words
    ['balloon', 'בלון', '🎈', 4, 'thing'], ['rainbow', 'קשת', '🌈', 4, 'thing'], ['penguin', 'פינגווין', '🐧', 4, 'animal'],
    ['umbrella', 'מטריה', '☂️', 4, 'thing'], ['mountain', 'הר', '⛰️', 4, 'thing'], ['chicken', 'תרנגול', '🐓', 4, 'animal'],
    ['butterfly', 'פרפר', '🦋', 4, 'animal'], ['dinosaur', 'דינוזאור', '🦖', 4, 'animal'], ['unicorn', 'חד קרן', '🦄', 4, 'animal'],
    ['octopus', 'תמנון', '🐙', 4, 'animal'], ['giraffe', 'ג׳ירפה', '🦒', 4, 'animal'], ['kangaroo', 'קנגורו', '🦘', 4, 'animal'],
    ['present', 'מתנה', '🎁', 4, 'thing'], ['treasure', 'אוצר', '💰', 4, 'thing'], ['computer', 'מחשב', '💻', 4, 'thing'],
    ['popcorn', 'פופקורן', '🍿', 4, 'food'], ['sandwich', 'כריך', '🥪', 4, 'food'], ['strawberry', 'תות', '🍓', 4, 'food'],
    ['sleepy', 'עייף', '🥱', 4, 'describe'], ['scared', 'מפוחד', '😨', 4, 'describe'],
    // ── round 3: more words ──
    ['toy', 'צעצוע', '🧸', 1, 'thing'], ['map', 'מפה', '🗺️', 1, 'thing'], ['cap', 'כובע מצחייה', '🧢', 1, 'thing'],
    ['van', 'טנדר', '🚐', 1, 'thing'], ['web', 'קורי עכביש', '🕸️', 1, 'thing'], ['sea', 'ים', '🌊', 1, 'thing'],
    ['rat', 'עכברוש', '🐀', 1, 'animal'], ['leg', 'רגל', '🦵', 1, 'body'], ['nut', 'אגוז', '🥜', 1, 'food'],
    ['pie', 'פאי', '🥧', 1, 'food'], ['tea', 'תה', '🍵', 1, 'food'], ['ice', 'קרח', '🧊', 1, 'thing'],
    ['boy', 'ילד', '👦', 1, 'thing'], ['old', 'זקן', '👴', 1, 'describe'], ['wet', 'רטוב', '💦', 1, 'describe'],
    ['hug', 'לחבק', '🤗', 1, 'action'], ['cry', 'לבכות', '😭', 1, 'action'], ['dig', 'לחפור', '⛏️', 1, 'action'],
    ['baby', 'תינוק', '👶', 2, 'thing'], ['king', 'מלך', '🤴', 2, 'thing'], ['queen', 'מלכה', '👸', 2, 'thing'],
    ['ghost', 'רוח רפאים', '👻', 2, 'thing'], ['bell', 'פעמון', '🔔', 2, 'thing'], ['tent', 'אוהל', '⛺', 2, 'thing'],
    ['lock', 'מנעול', '🔒', 2, 'thing'], ['coat', 'מעיל', '🧥', 2, 'thing'], ['dress', 'שמלה', '👗', 2, 'thing'],
    ['boot', 'מגף', '👢', 2, 'thing'], ['bike', 'אופניים', '🚲', 2, 'thing'], ['taxi', 'מונית', '🚕', 2, 'thing'],
    ['bath', 'אמבטיה', '🛁', 2, 'thing'], ['soap', 'סבון', '🧼', 2, 'thing'], ['bone', 'עצם', '🦴', 2, 'body'],
    ['brain', 'מוח', '🧠', 2, 'body'], ['crab', 'סרטן', '🦀', 2, 'animal'], ['snail', 'חילזון', '🐌', 2, 'animal'],
    ['goat', 'עז', '🐐', 2, 'animal'], ['wolf', 'זאב', '🐺', 2, 'animal'], ['deer', 'צבי', '🦌', 2, 'animal'],
    ['koala', 'קואלה', '🐨', 2, 'animal'], ['panda', 'פנדה', '🐼', 2, 'animal'], ['camel', 'גמל', '🐫', 2, 'animal'],
    ['whale', 'לווייתן', '🐋', 2, 'animal'], ['shark', 'כריש', '🦈', 2, 'animal'], ['swan', 'ברבור', '🦢', 2, 'animal'],
    ['llama', 'לאמה', '🦙', 2, 'animal'], ['hippo', 'היפופוטם', '🦛', 2, 'animal'], ['eagle', 'נשר', '🦅', 2, 'animal'],
    ['soup', 'מרק', '🍲', 2, 'food'], ['rice', 'אורז', '🍚', 2, 'food'], ['pear', 'אגס', '🍐', 2, 'food'],
    ['candy', 'סוכרייה', '🍬', 2, 'food'], ['juice', 'מיץ', '🧃', 2, 'food'], ['fries', 'צ׳יפס', '🍟', 2, 'food'],
    ['donut', 'סופגנייה', '🍩', 2, 'food'], ['taco', 'טאקו', '🌮', 2, 'food'], ['melon', 'מלון', '🍈', 2, 'food'],
    ['gray', 'אפור', 'c:#8c8c96', 2, 'color'], ['gold', 'זהב', 'c:#e8b830', 2, 'color'],
    ['fast', 'מהיר', '🏎️', 2, 'describe'], ['funny', 'מצחיק', '🤡', 2, 'describe'], ['sick', 'חולה', '🤒', 2, 'describe'],
    ['yummy', 'טעים', '😋', 2, 'describe'], ['loud', 'רועש', '📢', 2, 'describe'],
    ['clap', 'למחוא כפיים', '👏', 2, 'action'], ['wave', 'לנופף', '👋', 2, 'action'], ['think', 'לחשוב', '🤔', 2, 'action'],
    ['surf', 'לגלוש', '🏄', 2, 'action'], ['read', 'לקרוא', '📚', 2, 'action'], ['write', 'לכתוב', '✍️', 2, 'action'],
    ['sword', 'חרב', '🗡️', 2, 'thing'], ['phone', 'טלפון', '📱', 2, 'thing'], ['piano', 'פסנתר', '🎹', 2, 'thing'],
    ['alien', 'חייזר', '👽', 2, 'thing'],
    ['wizard', 'קוסם', '🧙', 3, 'thing'], ['shield', 'מגן', '🛡️', 3, 'thing'], ['magnet', 'מגנט', '🧲', 3, 'thing'],
    ['camera', 'מצלמה', '📷', 3, 'thing'], ['hammer', 'פטיש', '🔨', 3, 'thing'], ['planet', 'כוכב לכת', '🪐', 3, 'thing'],
    ['violin', 'כינור', '🎻', 3, 'thing'], ['school', 'בית ספר', '🏫', 3, 'thing'], ['parrot', 'תוכי', '🦜', 3, 'animal'],
    ['lizard', 'לטאה', '🦎', 3, 'animal'], ['squid', 'דיונון', '🦑', 3, 'animal'], ['otter', 'לוטרה', '🦦', 3, 'animal'],
    ['tractor', 'טרקטור', '🚜', 4, 'thing'], ['helicopter', 'מסוק', '🚁', 4, 'thing'], ['volcano', 'הר געש', '🌋', 4, 'thing'],
    ['trumpet', 'חצוצרה', '🎺', 4, 'thing'], ['pumpkin', 'דלעת', '🎃', 4, 'food'], ['glasses', 'משקפיים', '👓', 4, 'thing'],
    ['scissors', 'מספריים', '✂️', 4, 'thing'], ['ladybug', 'פרת משה רבנו', '🐞', 4, 'animal'], ['gorilla', 'גורילה', '🦍', 4, 'animal'],
    ['crocodile', 'תנין', '🐊', 4, 'animal'], ['flamingo', 'פלמינגו', '🦩', 4, 'animal'], ['peacock', 'טווס', '🦚', 4, 'animal'],
    ['dolphin', 'דולפין', '🐬', 4, 'animal'], ['watermelon', 'אבטיח', '🍉', 4, 'food'],
  ];
  const WORDS = W.map(([w, he, pic, tier, cat]) => ({ w, he, pic, tier, cat }));
  const BY = {};
  WORDS.forEach(o => (BY[o.w] = o));

  // Sentences. pics = what the picture shows. blank = index of the word hidden in "fill the gap" games.
  // Only words a beginner meets first (sight words + the word bank).
  const S = [
    ['I see a cat.', ['🐱'], 3, 1, 'אני רואה חתול.'],
    ['I see a big dog.', ['🐶'], 4, 1, 'אני רואה כלב גדול.'],
    ['The sun is hot.', ['☀️'], 1, 1, 'השמש חמה.'],
    ['I have a red apple.', ['🍎'], 3, 1, 'יש לי תפוח אדום.'],
    ['The fox can run.', ['🦊', '🏃'], 1, 1, 'השועל יכול לרוץ.'],
    ['I like my dog.', ['🐶', '❤️'], 1, 1, 'אני אוהב את הכלב שלי.'],
    ['It is a bee.', ['🐝'], 3, 1, 'זו דבורה.'],
    ['The cat is sad.', ['😿'], 3, 1, 'החתול עצוב.'],
    ['I have two eggs.', ['🥚', '🥚'], 2, 1, 'יש לי שתי ביצים.'],
    ['The pig is in the box.', ['🐷', '📦'], 1, 1, 'החזיר בתוך הקופסה.'],
    ['I see the moon.', ['🌙'], 3, 2, 'אני רואה את הירח.'],
    ['The fish can swim.', ['🐟'], 3, 2, 'הדג יכול לשחות.'],
    ['I like cake.', ['🍰'], 2, 2, 'אני אוהב עוגה.'],
    ['The frog can jump.', ['🐸'], 3, 2, 'הצפרדע יכולה לקפוץ.'],
    ['The ball is blue.', ['⚽'], 1, 2, 'הכדור כחול.'],
    ['I have a book.', ['📖'], 3, 2, 'יש לי ספר.'],
    ['The bird is in the tree.', ['🐦', '🌳'], 5, 2, 'הציפור על העץ.'],
    ['I am happy.', ['😊'], 2, 2, 'אני שמח.'],
    ['The duck is on the boat.', ['🦆', '⛵'], 5, 2, 'הברווז על הסירה.'],
    ['I see five stars.', ['⭐', '⭐', '⭐', '⭐', '⭐'], 2, 2, 'אני רואה חמישה כוכבים.'],
    ['The lion is big.', ['🦁'], 1, 2, 'האריה גדול.'],
    ['I can eat corn.', ['🌽'], 3, 2, 'אני יכול לאכול תירס.'],
    ['The bear can sleep.', ['🐻', '😴'], 1, 2, 'הדוב יכול לישון.'],
    ['I like milk.', ['🥛'], 2, 2, 'אני אוהב חלב.'],
    ['The dragon is green.', ['🐉'], 1, 3, 'הדרקון ירוק.'],
    ['I have an apple.', ['🍎'], 3, 3, 'יש לי תפוח.'],
    ['The rabbit can jump.', ['🐰'], 1, 3, 'הארנב יכול לקפוץ.'],
    ['This is my castle.', ['🏰'], 3, 3, 'זו הטירה שלי.'],
    ['I see a pink flower.', ['🌸'], 4, 3, 'אני רואה פרח ורוד.'],
    ['The water is cold.', ['💧', '🥶'], 1, 3, 'המים קרים.'],
    ['The cat is on the bed.', ['🐱', '🛏️'], 5, 2, 'החתול על המיטה.'],
    ['I have a big ball.', ['⚽'], 3, 2, 'יש לי כדור גדול.'],
    ['My dog is brown.', ['🐶'], 3, 2, 'הכלב שלי חום.'],
    ['The sun is in the sky.', ['☀️'], 1, 2, 'השמש בשמיים.'],
    ['I can see a ship.', ['🚢'], 4, 2, 'אני יכול לראות ספינה.'],
    ['The horse can run.', ['🐴', '🏃'], 1, 2, 'הסוס יכול לרוץ.'],
    ['The mouse is small.', ['🐁'], 3, 2, 'העכבר קטן.'],
    ['I like the rain.', ['🌧️'], 3, 2, 'אני אוהב את הגשם.'],
    ['The monkey is funny.', ['🐒'], 1, 3, 'הקוף מצחיק.'],
    ['I see a red rocket.', ['🚀'], 3, 3, 'אני רואה טיל אדום.'],
    ['The turtle is slow.', ['🐢'], 1, 3, 'הצב איטי.'],
    ['I have a pencil and a book.', ['✏️', '📖'], 3, 3, 'יש לי עיפרון וספר.'],
    ['The spider is on the wall.', ['🕷️'], 1, 3, 'העכביש על הקיר.'],
    ['We like to eat cookies.', ['🍪'], 1, 3, 'אנחנו אוהבים לאכול עוגיות.'],
    ['The tiger has a long tail.', ['🐯'], 1, 3, 'לנמר יש זנב ארוך.'],
    ['My cat can climb a tree.', ['🐱', '🌳'], 3, 3, 'החתול שלי יכול לטפס על עץ.'],
    ['There is a rainbow in the sky.', ['🌈'], 3, 4, 'יש קשת בשמיים.'],
    ['The penguin likes the cold snow.', ['🐧', '☃️'], 1, 4, 'הפינגווין אוהב את השלג הקר.'],
    ['I got a present from my mom.', ['🎁'], 3, 4, 'קיבלתי מתנה מאמא שלי.'],
    ['The dinosaur is very big.', ['🦖'], 1, 4, 'הדינוזאור גדול מאוד.'],
    ['She has a pink umbrella.', ['☂️'], 3, 4, 'יש לה מטריה ורודה.'],
    ['The butterfly is on the flower.', ['🦋', '🌸'], 1, 4, 'הפרפר על הפרח.'],
    ['We can see the big mountain.', ['⛰️'], 3, 4, 'אנחנו יכולים לראות את ההר הגדול.'],
    ['The octopus lives in the sea.', ['🐙'], 2, 4, 'התמנון גר בים.'],
    // ── round 3: more sentences ──
    ['I see a crab.', ['🦀'], 3, 1, 'אני רואה סרטן.'],
    ['The rat is in the box.', ['🐀', '📦'], 1, 1, 'העכברוש בתוך הקופסה.'],
    ['I have a toy.', ['🧸'], 3, 1, 'יש לי צעצוע.'],
    ['My hat is red.', ['🎩'], 1, 1, 'הכובע שלי אדום.'],
    ['The cow is big.', ['🐮'], 1, 1, 'הפרה גדולה.'],
    ['I can run.', ['🏃'], 2, 1, 'אני יכול לרוץ.'],
    ['I have a map.', ['🗺️'], 3, 1, 'יש לי מפה.'],
    ['I like my cap.', ['🧢'], 3, 1, 'אני אוהב את הכובע שלי.'],
    ['The bus is hot.', ['🚌', '☀️'], 1, 1, 'האוטובוס חם.'],
    ['I see a web.', ['🕸️'], 3, 1, 'אני רואה קורי עכביש.'],
    ['The ant is on my arm.', ['🐜', '💪'], 1, 1, 'הנמלה על הזרוע שלי.'],
    ['I like tea.', ['🍵'], 2, 1, 'אני אוהב תה.'],
    ['The hen has an egg.', ['🐔', '🥚'], 1, 1, 'לתרנגולת יש ביצה.'],
    ['The boy is wet.', ['👦', '💦'], 3, 1, 'הילד רטוב.'],
    ['I see the sea.', ['🌊'], 3, 1, 'אני רואה את הים.'],
    ['The whale is in the sea.', ['🐋', '🌊'], 1, 2, 'הלווייתן בים.'],
    ['The snail is in the rain.', ['🐌', '🌧️'], 1, 2, 'החילזון בגשם.'],
    ['I like hot soup.', ['🍲'], 3, 2, 'אני אוהב מרק חם.'],
    ['The king has a crown.', ['🤴', '👑'], 1, 2, 'למלך יש כתר.'],
    ['The queen is happy.', ['👸', '😊'], 1, 2, 'המלכה שמחה.'],
    ['I have a blue bike.', ['🚲'], 4, 2, 'יש לי אופניים כחולים.'],
    ['The ghost is white.', ['👻'], 3, 2, 'רוח הרפאים לבנה.'],
    ['The goat can jump.', ['🐐'], 1, 2, 'העז יכולה לקפוץ.'],
    ['I see a black wolf.', ['🐺'], 3, 2, 'אני רואה זאב שחור.'],
    ['The panda likes to eat.', ['🐼'], 1, 2, 'הפנדה אוהבת לאכול.'],
    ['My coat is green.', ['🧥'], 1, 2, 'המעיל שלי ירוק.'],
    ['I have a pink dress.', ['👗'], 4, 2, 'יש לי שמלה ורודה.'],
    ['The baby can clap.', ['👶', '👏'], 1, 2, 'התינוק יכול למחוא כפיים.'],
    ['I like juice and fries.', ['🧃', '🍟'], 2, 2, 'אני אוהב מיץ וצ׳יפס.'],
    ['The shark can swim.', ['🦈'], 1, 2, 'הכריש יכול לשחות.'],
    ['I see a big tent.', ['⛺'], 4, 2, 'אני רואה אוהל גדול.'],
    ['The crab is on the rock.', ['🦀', '🪨'], 1, 2, 'הסרטן על האבן.'],
    ['I can wave my hand.', ['👋', '✋'], 4, 2, 'אני יכול לנופף ביד.'],
    ['The bird can sing.', ['🐦', '🎤'], 1, 2, 'הציפור יכולה לשיר.'],
    ['The koala is in the tree.', ['🐨', '🌳'], 1, 2, 'הקואלה על העץ.'],
    ['The camel is brown.', ['🐫'], 3, 2, 'הגמל חום.'],
    ['I can read a book.', ['📚', '📖'], 4, 2, 'אני יכול לקרוא ספר.'],
    ['The clown is funny.', ['🤡'], 3, 2, 'הליצן מצחיק.'],
    ['The car is fast.', ['🏎️'], 3, 2, 'המכונית מהירה.'],
    ['I wash my hand with soap.', ['🧼', '✋'], 5, 2, 'אני שוטף את היד עם סבון.'],
    ['The eagle can fly.', ['🦅'], 1, 2, 'הנשר יכול לעוף.'],
    ['I am sick in bed.', ['🤒', '🛏️'], 2, 2, 'אני חולה במיטה.'],
    ['The donut is yummy.', ['🍩', '😋'], 1, 2, 'הסופגנייה טעימה.'],
    ['The wizard has a magic hat.', ['🧙', '🎩'], 1, 3, 'לקוסם יש כובע קסמים.'],
    ['The parrot can talk.', ['🦜'], 1, 3, 'התוכי יכול לדבר.'],
    ['I play the piano.', ['🎹'], 3, 3, 'אני מנגן בפסנתר.'],
    ['My robot can dance.', ['🤖', '💃'], 1, 3, 'הרובוט שלי יכול לרקוד.'],
    ['The alien has a green rocket.', ['👽', '🚀'], 1, 3, 'לחייזר יש טיל ירוק.'],
    ['The lizard is on a rock.', ['🦎', '🪨'], 1, 3, 'הלטאה על אבן.'],
    ['I have a camera and a phone.', ['📷', '📱'], 3, 3, 'יש לי מצלמה וטלפון.'],
    ['The hippo likes the water.', ['🦛', '💧'], 1, 3, 'ההיפופוטם אוהב את המים.'],
    ['My sister has a red guitar.', ['🎸'], 5, 3, 'לאחות שלי יש גיטרה אדומה.'],
    ['We can hear the bell.', ['🔔'], 4, 3, 'אנחנו יכולים לשמוע את הפעמון.'],
    ['The cheese is yellow.', ['🧀'], 1, 3, 'הגבינה צהובה.'],
    ['Dad has a big hammer.', ['🔨'], 4, 3, 'לאבא יש פטיש גדול.'],
    ['I put on my coat.', ['🧥'], 4, 3, 'אני לובש את המעיל שלי.'],
    ['The knight has a sword and a shield.', ['🗡️', '🛡️'], 7, 3, 'לאביר יש חרב ומגן.'],
    ['The magnet can pick up a key.', ['🧲', '🔑'], 1, 3, 'המגנט יכול להרים מפתח.'],
    ['I go to school every day.', ['🏫'], 3, 3, 'אני הולך לבית הספר כל יום.'],
    ['The otter can swim on its back.', ['🦦'], 1, 3, 'הלוטרה יכולה לשחות על הגב.'],
    ['There is a volcano on the island.', ['🌋', '🏝️'], 3, 4, 'יש הר געש על האי.'],
    ['The dolphin can jump out of the water.', ['🐬', '💧'], 1, 4, 'הדולפין יכול לקפוץ מתוך המים.'],
    ['I see a helicopter in the sky.', ['🚁'], 3, 4, 'אני רואה מסוק בשמיים.'],
    ['The flamingo stands on one leg.', ['🦩', '🦵'], 1, 4, 'הפלמינגו עומד על רגל אחת.'],
    ['We have a big orange pumpkin.', ['🎃'], 5, 4, 'יש לנו דלעת כתומה גדולה.'],
    ['The crocodile has big teeth.', ['🐊'], 1, 4, 'לתנין יש שיניים גדולות.'],
    ['My grandma has new glasses.', ['👓'], 4, 4, 'לסבתא שלי יש משקפיים חדשים.'],
    ['The gorilla eats a banana.', ['🦍', '🍌'], 1, 4, 'הגורילה אוכלת בננה.'],
    ['The farmer drives a big tractor.', ['🚜'], 5, 4, 'החקלאי נוהג בטרקטור גדול.'],
    ['The ladybug is red and black.', ['🐞'], 1, 4, 'פרת משה רבנו אדומה ושחורה.'],
    ['I can play the trumpet.', ['🎺'], 4, 4, 'אני יכול לנגן בחצוצרה.'],
    ['The peacock has a long tail.', ['🦚'], 1, 4, 'לטווס יש זנב ארוך.'],
    ['Please give me the scissors.', ['✂️'], 4, 4, 'בבקשה תן לי את המספריים.'],
    ['We eat watermelon in the summer.', ['🍉'], 2, 4, 'אנחנו אוכלים אבטיח בקיץ.'],
  ];
  const SENTENCES = S.map(([text, pics, blank, tier, he]) => {
    const words = text.replace('.', '').split(' ');
    return { text, words, pics, blank, tier, he };
  });

  // short praise lines — spoken and shown, so they are reading practice too
  const PRAISE = ['Great!', 'Good job!', 'Yes!', 'Super!', 'Well done!', 'You did it!', 'Wow!', 'Nice!'];
  const TRY = ['Try again!', 'Almost!', 'Oops! Look again.'];

  // ── verbs for the tense games: base, he/she form, past, picture, Hebrew, object (optional) ──
  const V = [
    ['jump', 'jumps', 'jumped', '🦘', 'לקפוץ', ''], ['play', 'plays', 'played', '🎮', 'לשחק', 'a game'],
    ['dance', 'dances', 'danced', '💃', 'לרקוד', ''], ['cook', 'cooks', 'cooked', '🍳', 'לבשל', 'an egg'],
    ['walk', 'walks', 'walked', '🚶', 'ללכת', 'to the park'], ['paint', 'paints', 'painted', '🎨', 'לצבוע', 'a house'],
    ['kick', 'kicks', 'kicked', '⚽', 'לבעוט', 'the ball'], ['climb', 'climbs', 'climbed', '🧗', 'לטפס', 'a tree'],
    ['wash', 'washes', 'washed', '🧽', 'לשטוף', 'the car'], ['open', 'opens', 'opened', '🚪', 'לפתוח', 'the door'],
    ['laugh', 'laughs', 'laughed', '😂', 'לצחוק', ''], ['clean', 'cleans', 'cleaned', '🧹', 'לנקות', 'the room'],
    ['help', 'helps', 'helped', '🤝', 'לעזור', 'my friend'], ['cry', 'cries', 'cried', '😢', 'לבכות', ''],
    ['swim', 'swims', 'swam', '🏊', 'לשחות', 'in the sea'], ['eat', 'eats', 'ate', '🍎', 'לאכול', 'an apple'],
    ['run', 'runs', 'ran', '🏃', 'לרוץ', ''], ['sleep', 'sleeps', 'slept', '😴', 'לישון', 'in bed'],
    ['sing', 'sings', 'sang', '🎤', 'לשיר', 'a song'], ['drink', 'drinks', 'drank', '🥛', 'לשתות', 'milk'],
    ['ride', 'rides', 'rode', '🚲', 'לרכוב', 'a bike'], ['fly', 'flies', 'flew', '🪁', 'להעיף', 'a kite'],
    ['see', 'sees', 'saw', '👀', 'לראות', 'a bird'], ['make', 'makes', 'made', '🎂', 'להכין', 'a cake'],
    ['draw', 'draws', 'drew', '✏️', 'לצייר', 'a cat'], ['go', 'goes', 'went', '🏫', 'ללכת', 'to school'],
    // ── round 3: more verbs ──
    ['look', 'looks', 'looked', '🔭', 'להסתכל', 'at the moon'], ['listen', 'listens', 'listened', '🎧', 'להקשיב', 'to music'],
    ['watch', 'watches', 'watched', '📺', 'לצפות', 'TV'], ['call', 'calls', 'called', '📞', 'להתקשר', 'my friend'],
    ['visit', 'visits', 'visited', '🏡', 'לבקר', 'the zoo'], ['brush', 'brushes', 'brushed', '🦷', 'לצחצח', 'my teeth'],
    ['bake', 'bakes', 'baked', '🍪', 'לאפות', 'cookies'], ['fix', 'fixes', 'fixed', '🔧', 'לתקן', 'the bike'],
    ['plant', 'plants', 'planted', '🌱', 'לשתול', 'a flower'], ['hug', 'hugs', 'hugged', '🤗', 'לחבק', 'the baby'],
    ['smile', 'smiles', 'smiled', '😁', 'לחייך', ''], ['carry', 'carries', 'carried', '🎒', 'לסחוב', 'a bag'],
    ['push', 'pushes', 'pushed', '🛒', 'לדחוף', 'the cart'], ['shout', 'shouts', 'shouted', '📢', 'לצעוק', ''],
    ['write', 'writes', 'wrote', '✍️', 'לכתוב', 'a letter'], ['catch', 'catches', 'caught', '🧤', 'לתפוס', 'the ball'],
    ['throw', 'throws', 'threw', '🥏', 'לזרוק', 'a ball'], ['buy', 'buys', 'bought', '🛍️', 'לקנות', 'a toy'],
    ['build', 'builds', 'built', '🧱', 'לבנות', 'a castle'], ['drive', 'drives', 'drove', '🚗', 'לנהוג', 'a car'],
    ['find', 'finds', 'found', '🔍', 'למצוא', 'a shell'], ['sit', 'sits', 'sat', '🪑', 'לשבת', 'on a chair'],
    ['win', 'wins', 'won', '🏆', 'לנצח', 'the game'], ['come', 'comes', 'came', '🏠', 'לבוא', 'home'],
    ['fall', 'falls', 'fell', '🍂', 'ליפול', ''], ['dig', 'digs', 'dug', '⛏️', 'לחפור', 'a hole'],
    ['feed', 'feeds', 'fed', '🥕', 'להאכיל', 'the horse'], ['take', 'takes', 'took', '📸', 'לצלם', 'a photo'],
  ];
  const VERBS = V.map(([v, s3, past, pic, he, obj]) => ({ v, s3, past, pic, he, obj, regular: /ed$/.test(past) }));
  // who does it. third = says "jumps" in the present
  const SUBJECTS = [
    { w: 'I', pic: '🙋', third: false, he: 'אני' }, { w: 'You', pic: '👉', third: false, he: 'אתה' },
    { w: 'We', pic: '👫', third: false, he: 'אנחנו' }, { w: 'They', pic: '👪', third: false, he: 'הם' },
    { w: 'He', pic: '👦', third: true, he: 'הוא' }, { w: 'She', pic: '👧', third: true, he: 'היא' },
    { w: 'The cat', pic: '🐱', third: true, he: 'החתול' }, { w: 'The dog', pic: '🐶', third: true, he: 'הכלב' },
    { w: 'The fox', pic: '🦊', third: true, he: 'השועל' }, { w: 'My mom', pic: '👩', third: true, he: 'אמא שלי' },
    { w: 'My dad', pic: '👨', third: true, he: 'אבא שלי' }, { w: 'My grandma', pic: '👵', third: true, he: 'סבתא שלי' },
    { w: 'The bird', pic: '🐦', third: true, he: 'הציפור' }, { w: 'The dragon', pic: '🐉', third: true, he: 'הדרקון' },
  ];
  const TIMES = {
    past: [{ w: 'yesterday', he: 'אתמול' }, { w: 'last night', he: 'אתמול בלילה' }, { w: 'last week', he: 'בשבוע שעבר' }, { w: 'last year', he: 'בשנה שעברה' }],
    now: [{ w: 'every day', he: 'כל יום' }, { w: 'every morning', he: 'כל בוקר' }, { w: 'every night', he: 'כל לילה' }, { w: 'every week', he: 'כל שבוע' }],
    future: [{ w: 'tomorrow', he: 'מחר' }, { w: 'next week', he: 'בשבוע הבא' }, { w: 'next year', he: 'בשנה הבאה' }, { w: 'soon', he: 'בקרוב' }],
  };
  // the verb as it appears in the sentence
  const form = (vb, when, subj) => when === 'past' ? vb.past : when === 'future' ? 'will ' + vb.v : (subj.third ? vb.s3 : vb.v);
  // a generated sentence: "The cat jumped yesterday."
  function tenseSentence(vb, when, subj, opts) {
    opts = opts || {};
    const time = opts.noTime ? null : TIMES[when][Math.floor(Math.random() * TIMES[when].length)];
    const vf = form(vb, when, subj);
    const verbW = vf.split(' '), objW = vb.obj ? vb.obj.split(' ') : [], timeW = time ? time.w.split(' ') : [];
    let head = subj.w.split(' '), words;
    if (opts.timeFirst && time) {
      // "Yesterday the cat jumped."
      const tw = timeW.slice(); tw[0] = tw[0][0].toUpperCase() + tw[0].slice(1);
      if (head[0] !== 'I') head = [head[0].toLowerCase()].concat(head.slice(1));
      head = tw.concat(head);
      words = head.concat(verbW, objW);
    } else words = head.concat(verbW, objW, timeW);
    return { text: words.join(' ') + '.', words, verbAt: head.length, verbLen: verbW.length, verbForm: vf, when, vb, subj, time, pics: [subj.pic, vb.pic],
      he: [subj.he, vb.he, time ? time.he : ''].filter(Boolean).join(' · ') };
  }

  window.WB = { WORDS, BY, SENTENCES, PRAISE, TRY, VERBS, SUBJECTS, TIMES, form, tenseSentence };
})();
